"""
Pydantic data contracts — single source of truth for all message schemas.
Every producer, consumer, and agent must validate against these models.
Changing a field here is a breaking change — treat it as a versioned API.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class VitalSigns(BaseModel):
    """
    Validated vital signs from a bedside monitor.
    All ranges are clinical plausibility bounds, not normal ranges.
    """
    heart_rate_bpm: int = Field(
        ..., ge=20, le=300,
        description="Heart rate in beats per minute"
    )
    systolic_bp_mmhg: int = Field(
        ..., ge=50, le=260,
        description="Systolic blood pressure in mmHg"
    )
    diastolic_bp_mmhg: int = Field(
        ..., ge=30, le=160,
        description="Diastolic blood pressure in mmHg"
    )
    spo2_percent: float = Field(
        ..., ge=50.0, le=100.0,
        description="Peripheral oxygen saturation as percentage"
    )
    respiratory_rate_rpm: int = Field(
        ..., ge=4, le=60,
        description="Respiratory rate in breaths per minute"
    )
    temperature_celsius: float = Field(
        ..., ge=32.0, le=43.0,
        description="Body temperature in degrees Celsius"
    )

    @model_validator(mode="after")
    def validate_bp_relationship(self) -> VitalSigns:
        if self.diastolic_bp_mmhg >= self.systolic_bp_mmhg:
            raise ValueError(
                f"Diastolic BP ({self.diastolic_bp_mmhg} mmHg) must be "
                f"less than systolic BP ({self.systolic_bp_mmhg} mmHg)"
            )
        return self


class TelemetryEvent(BaseModel):
    """
    Top-level message published to `clinical_telemetry` topic.
    Kafka message key = patient_id (ensures partition locality + ordering).
    """
    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique event UUID — generated at source"
    )
    patient_id: str = Field(
        ..., min_length=4, max_length=32,
        description="Patient identifier, format: PT-XXX"
    )
    hospital_id: str = Field(
        ..., description="Originating hospital identifier"
    )
    ward: str = Field(..., description="Hospital ward name")
    bed_number: str = Field(..., description="Bed identifier within ward")
    timestamp_utc: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Event timestamp in UTC"
    )
    vitals: VitalSigns
    nursing_notes: Optional[str] = Field(
        None, max_length=1000,
        description="Free-text nursing observation, if recorded"
    )
    is_simulated: bool = Field(
        False,
        description="True when generated by the hospital simulator"
    )

    @field_validator("patient_id")
    @classmethod
    def validate_patient_id_format(cls, v: str) -> str:
        if not v.upper().startswith("PT-"):
            raise ValueError(
                f"patient_id must start with 'PT-', got: '{v}'"
            )
        return v.upper()


class CriticalAlert(BaseModel):
    """
    Published to `critical_alerts` topic by the CEP engine.
    This is the primary input contract for the LangGraph agent in Phase 2.
    All downstream consumers must validate against this schema.
    """
    alert_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique alert UUID — generated by CEP engine"
    )
    source_event_id: str = Field(
        ..., description="event_id of the originating TelemetryEvent"
    )
    patient_id: str
    hospital_id: str
    ward: str
    bed_number: str
    timestamp_utc: datetime
    severity: AlertSeverity
    triggered_rules: list[str] = Field(
        ...,
        description="Human-readable descriptions of every CEP rule that fired"
    )
    vitals_snapshot: VitalSigns = Field(
        ...,
        description="Exact vitals at the moment of alert — immutable snapshot"
    )
    nursing_notes: Optional[str] = None

    @property
    def summary(self) -> str:
        """One-line human-readable alert summary for logging."""
        rules = ", ".join(self.triggered_rules)
        return (
            f"[{self.severity.value}] {self.patient_id} "
            f"@ {self.ward}/{self.bed_number} — {rules}"
        )